# Generated by Django 2.2.8 on 2020-01-10 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='photos/%Y/%m/%d/')),
                ('postion', models.CharField(blank=True, choices=[('telecaller', 'Telecaller'), ('frontdesk', 'Front Desk'), ('counselor', 'Counselor'), ('bde', 'BDE'), ('admin', 'Admin'), ('developer', 'Developer'), ('manager', 'Manager'), ('seniormanager', 'Senior Manager')], max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('STD', 'base employee'), ('TL', 'team leader'), ('MGR', 'manager'), ('SRMGR', 'senior manager'), ('PRES', 'president')], max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_city', models.CharField(blank=True, choices=[('Bangalore', 'Bangalore'), ('Coimbatore', 'Coimbatore')], default='', max_length=200, null=True)),
                ('is_eom', models.BooleanField(blank=True, default=False, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='employees.Employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
