# Generated by Django 2.2.8 on 2020-01-10 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DTS',
            fields=[
                ('dated', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True)),
                ('timed', models.TimeField(default=datetime.time(20, 2, 20, 28320))),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporter', to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TargetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_data', to='records.DTS')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('telecaller', 'Telecaller'), ('frontdesk', 'Front Desk'), ('counselor', 'Counselor'), ('bde', 'BDE'), ('admin', 'Admin'), ('developer', 'Developer'), ('manager', 'Manager'), ('seniormanager', 'Senior Manager')], default='', max_length=100)),
                ('month', models.CharField(default='January', max_length=50)),
                ('submitted_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Created On')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCustomTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Custom Target')),
                ('value', models.IntegerField(blank=True, default=0, help_text='Integers only, no decimals', null=True)),
                ('monthly_target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_target', to='records.MonthlyTarget')),
            ],
        ),
        migrations.CreateModel(
            name='EmpRecord',
            fields=[
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('report_for', models.CharField(default='2020-January', max_length=50, primary_key=True, serialize=False, verbose_name='Report For')),
                ('month', models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='January', max_length=50, null=True, verbose_name='Month')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpCustomRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Custom Records')),
                ('value', models.IntegerField(blank=True, default=0, help_text='Integers only, no decimals', null=True)),
                ('emp_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_record', to='records.EmpRecord')),
            ],
        ),
        migrations.CreateModel(
            name='AchievedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_data', to='records.DTS')),
            ],
        ),
    ]
