# Generated by Django 2.2.8 on 2020-01-11 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dts',
            name='timed',
            field=models.TimeField(default=datetime.time(16, 58, 15, 355468)),
        ),
    ]
